### PR TITLE
bump `tiberius` from 0.11 to 0.12

### PR DESCRIPTION
**Pull request by xrelkd**

### CODE REVIEW

**Comment by xrelkd** [comment]
This pull request solved the issue https://github.com/kardeiz/bb8-tiberius/issues/21.

**Comment by xrelkd** [comment]
Hi, @kardeiz
Is there any improvement I can do for this PR?
Thank you!

**Comment by kardeiz** [comment]
Hey, sorry! No, I just didn't see your PR or issue. I just made a new release of bb8-tiberius with your PR.

I looked at a bunch of my Github repos, and about half of them I was just watching "Participating and @mentions", and the other half were "All activity". I don't think I've ever bothered to change these one way or the other. In any case, I just updated this repo to "All activity", so hopefully I will see yours and others' PRs more quickly in the future.

**Comment by xrelkd** [comment]
@kardeiz Thank you very much!

**Pull request merged**
